version: '3.8'

services:
  backend:
    image: backend:v1.0
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    ports:
      - "3001:3001"
    networks:
      - backend-network

  mysql:
    image: mysql:latest
    env_file:
      - .env.db
    ports:
      - "3306:3306"
    networks:
      - backend-network
    volumes:
      - mysql-data:/var/lib/mysql

networks:
  backend-network:
    driver: bridge

volumes:
  mysql-data: